### ISSUE TITLE
fix unit test in development

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR#36]
test_analysis.py is failing

**Comment by DavidLP** [comment]
Seems to be conda related. With my python under windows it works.

**Comment by DavidLP** [comment]
Travis does not fail

**Comment by DavidLP** [comment]
It fails because of your bug comitted here: https://github.com/SiLab-Bonn/pyBAR/commit/946014cc8fff1693754f1f10bed4f92d48270871

What was the reason to do that?

**Comment by DavidLP** [comment]
I revert.

**Comment by laborleben** [comment]
The interface of the clusterizer changed. Probably I was to enthusiastic and deleted more than necessary.

**Comment by DavidLP** [comment]
The API did not really change, but more needed features were implemented. The needed clusterizer version >= 2.3.0 is a released version hosted on PyPI. 
All the problems where there, because not the latest clusterizer version was used. The correct and working version was always mentioned in the requirenment.txt of pybar. I close this issue.

**Comment by laborleben** [comment]
there was version 2.2 still in my site-packages... funny that other packages were working ok.
