### ISSUE TITLE
Binary search algorithms could be slightly improved

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/pyBAR#86]
There is one special case where we could find a better value:
Imagine:
- We are at the last iteration: `TDAC = 1111` with `Occ = N_inj`: means threshold is still too low
- Then we do the additional last bit = 0 iteration: `TDAC = 1110` with `Occ = N_inj - 1`. Here we measure just by statistical error one count less. Than this result is taken. But we know already that even `TDAC = 1111` was still too low bad. This information could be used to prevent this.

Solution:
Do not do / use the last iteration result when all preceding bits are set.

**Comment by laborleben** [comment]
Don't we have these issues with every scan step? The issue is more likely to appear for the LSB, but also the tuning error is the smallest for the LSB being wrong.
I don't see how we can solve this and get significant better results.

A solution would be to increase the number of injections - this is equivalent to increased statistics.

**Comment by DavidLP** [comment]
Significant better results not, but a cross check that threashol(TDAC) is monotone could inprove the result.

**Comment by laborleben** [comment]
We store the best result in all tunings. Event if binary search does not give a good result we will overwrite with the optimal result afterwards.

E.g. 
10000 -> first step
...
11100 -> this is optimal result, but a little bit too high
11010 -> this in 3nd optimal result, but too low
11011 -> this in 2nd optimal result, but a little too low
11010 -> repeating last scan step with 0 (see above) -> change to 11011
11100 -> replaced 11011 with 11100, because the latter was better
